### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [git-girl/pseudo-projectile-plugin#6]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by git-girl** [comment]
oh wow that's really cool, thanks! and i added a license :) 

i think i'll clean up some things in the next days, and leave the nvim integration sitting for a while then and get the zsh part down nicely.
